CREATE TABLE `publication` (
    `id` INT NOT NULL AUTO_INCREMENT , 
    `title` TEXT NOT NULL , 
    `originalTitle` TEXT NULL , 
    `subTitle` TEXT NULL , 
    `originalLanguage` VARCHAR(10) NULL , 
    `publicationLanguage` VARCHAR(10) NOT NULL , 
    `translator` VARCHAR(255) NULL,
    `authors` TEXT NULL , `authorCode` VARCHAR(5) NOT NULL , 
    `themeCode` VARCHAR(10) NOT NULL , `isbn` VARCHAR(20) NULL , 
    `publisher` VARCHAR(255) NULL , `pubDate` INT NULL , 
    `pubOriginalDate` INT NULL , 
    `pubPlace` VARCHAR(255) NULL , 
    `subjects` TEXT NULL , 
    `pagesNumber` INT NULL , 
    `edition` VARCHAR(20) NULL , 
    `volume` VARCHAR(20) NULL , 
    `createdAt` DATETIME NOT NULL , 
    `createdBy` INT NOT NULL , 
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
    `updatedBy` INT NOT NULL , 
    PRIMARY KEY (`id`), 
    UNIQUE `isbn` (`isbn`)
) ENGINE = MyISAM;
